# Workflow name
name: Chromatic

# Event for the workflow
on:
    push:
        branches:
            - master
        paths:
            - 'packages/components/**'
    workflow_dispatch:

# List of jobs
jobs:
    chromatic-deployment:
        # Operating System
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Publish to Chromatic
              run: |
                  cd packages/components
                  pnpm run chromatic
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
