# Workflow name
name: Chromatic

# Event for the workflow
on:
    push:
        branches:
            - master
        paths:
            - 'packages/components/**'
    workflow_dispatch:

# List of jobs
jobs:
    chromatic-deployment:
        # Operating System
        runs-on: ubuntu-latest
        # Job steps
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: yarn
            - name: Build
              run: yarn build
            - name: Publish to Chromatic
              run: |
                  cd packages/components
                  yarn chromatic
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
